//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLayerLibrary.SR_CarDatabaseService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SR_CarDatabaseService.ICarDataService")]
    public interface ICarDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarDataService/SelectAllCars", ReplyAction="http://tempuri.org/ICarDataService/SelectAllCarsResponse")]
        SharedType.Auto[] SelectAllCars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarDataService/SelectAllCars", ReplyAction="http://tempuri.org/ICarDataService/SelectAllCarsResponse")]
        System.Threading.Tasks.Task<SharedType.Auto[]> SelectAllCarsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarDataService/InsertCar", ReplyAction="http://tempuri.org/ICarDataService/InsertCarResponse")]
        bool InsertCar(string name, string type, System.Nullable<int> kw, System.Nullable<int> miles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarDataService/InsertCar", ReplyAction="http://tempuri.org/ICarDataService/InsertCarResponse")]
        System.Threading.Tasks.Task<bool> InsertCarAsync(string name, string type, System.Nullable<int> kw, System.Nullable<int> miles);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICarDataServiceChannel : ServiceLayerLibrary.SR_CarDatabaseService.ICarDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarDataServiceClient : System.ServiceModel.ClientBase<ServiceLayerLibrary.SR_CarDatabaseService.ICarDataService>, ServiceLayerLibrary.SR_CarDatabaseService.ICarDataService {
        
        public CarDataServiceClient() {
        }
        
        public CarDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SharedType.Auto[] SelectAllCars() {
            return base.Channel.SelectAllCars();
        }
        
        public System.Threading.Tasks.Task<SharedType.Auto[]> SelectAllCarsAsync() {
            return base.Channel.SelectAllCarsAsync();
        }
        
        public bool InsertCar(string name, string type, System.Nullable<int> kw, System.Nullable<int> miles) {
            return base.Channel.InsertCar(name, type, kw, miles);
        }
        
        public System.Threading.Tasks.Task<bool> InsertCarAsync(string name, string type, System.Nullable<int> kw, System.Nullable<int> miles) {
            return base.Channel.InsertCarAsync(name, type, kw, miles);
        }
    }
}
