//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLayerLibrary.SR_CarService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SR_CarService.IKwConvertService")]
    public interface IKwConvertService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKwConvertService/PsToKw", ReplyAction="http://tempuri.org/IKwConvertService/PsToKwResponse")]
        int PsToKw(int ps);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKwConvertService/PsToKw", ReplyAction="http://tempuri.org/IKwConvertService/PsToKwResponse")]
        System.Threading.Tasks.Task<int> PsToKwAsync(int ps);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKwConvertServiceChannel : ServiceLayerLibrary.SR_CarService.IKwConvertService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KwConvertServiceClient : System.ServiceModel.ClientBase<ServiceLayerLibrary.SR_CarService.IKwConvertService>, ServiceLayerLibrary.SR_CarService.IKwConvertService {
        
        public KwConvertServiceClient() {
        }
        
        public KwConvertServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KwConvertServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KwConvertServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KwConvertServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int PsToKw(int ps) {
            return base.Channel.PsToKw(ps);
        }
        
        public System.Threading.Tasks.Task<int> PsToKwAsync(int ps) {
            return base.Channel.PsToKwAsync(ps);
        }
    }
}
